version: '3'

services:

  server-django:
    container_name: django_server
    build:  
      context: ./backend
    ports:
      - "8080:8000"
    env_file:
      - .env.dev
    volumes:
      - ./backend:/app
    depends_on:
      - postgres_db

  client-react:
    container_name: react_client
    build:
      context: ./frontend_ts
    volumes:
      - ./frontend_ts:/app
    ports:
      - "30:3000"


  postgres_db:
    image: postgres:14-alpine3.17
    container_name: postgres_db
    ports:
    - "5433:5432"
    env_file:
      - .env.dev
    volumes:
      - pgdata:/var/lib/postgresql/data/
volumes:
 pgdata:



