# Generated by Django 4.2.3 on 2023-07-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_article_authors_projectpresentation_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
    ]
