# Generated by Django 4.2.3 on 2023-09-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_article_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание раздела')),
                ('name', models.CharField(max_length=255, verbose_name='Название баннера')),
                ('banner', models.ImageField(upload_to='banners/', verbose_name='Баннер')),
            ],
        ),
    ]
