# Generated by Django 4.2.3 on 2023-09-19 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0006_movie_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='st88rating',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ST88ratings', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
