# Generated by Django 4.2.3 on 2023-10-20 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='user/avatar', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 13, 4, 4, 787479, tzinfo=datetime.timezone.utc), null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='url',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
