# Generated by Django 4.2.3 on 2023-10-20 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_alter_profile_options_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='synopsys',
            field=models.TextField(null=True, verbose_name='Краткое содержание'),
        ),
        migrations.AddField(
            model_name='projectpresentation',
            name='release_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='release_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='st88description',
            name='release_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='st88project',
            name='release_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='article',
            name='release_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='user/avatar/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='st88project',
            name='linked_film',
            field=models.CharField(max_length=500, null=True, verbose_name='Ссылка на фильм'),
        ),
    ]
