# Generated by Django 4.2.3 on 2023-10-20 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0011_article_synopsys_projectpresentation_release_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('link', models.CharField(max_length=255, null=True, verbose_name='Ссылка')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Дата публикации')),
                ('authors', models.ManyToManyField(related_name='educations', to=settings.AUTH_USER_MODEL, verbose_name='Авторы')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='API.course', verbose_name='Курс')),
            ],
        ),
    ]
