# Generated by Django 4.2.3 on 2023-10-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_course_education'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курсы', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Образование', 'verbose_name_plural': 'Образование'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='music',
            field=models.FileField(blank=True, null=True, upload_to='movie/music/', verbose_name='Музыка'),
        ),
    ]
