# Generated by Django 4.2.3 on 2023-10-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_alter_course_options_alter_education_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на трейлер'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
