# Generated by Django 4.2.3 on 2023-10-30 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_alter_movie_link_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='st88project',
            name='url',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='st88project',
            name='downloaded_film',
            field=models.FileField(blank=True, null=True, upload_to='ST88/projects/', verbose_name='Загруженный фильм'),
        ),
        migrations.AlterField(
            model_name='st88project',
            name='linked_film',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на фильм'),
        ),
        migrations.AlterField(
            model_name='st88project',
            name='scenario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ST88_project', to='API.scenario', verbose_name='Сценарий'),
        ),
        migrations.AlterField(
            model_name='st88project',
            name='synopsys',
            field=models.TextField(verbose_name='Синопсис'),
        ),
    ]
