# Generated by Django 4.2.3 on 2023-11-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0017_st88description_rating_alter_profile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='st88description',
            name='rating',
        ),
    ]
