# Generated by Django 4.2.3 on 2023-11-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0018_remove_st88description_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='st88description',
            options={'verbose_name': 'СТ88 Описание и Рейтинг', 'verbose_name_plural': 'СТ88 Описания и Рейтинги'},
        ),
        migrations.AddField(
            model_name='st88description',
            name='rating',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Рейтинг ST88'),
        ),
        migrations.AlterField(
            model_name='st88description',
            name='description',
            field=models.TextField(verbose_name='Описание ST88'),
        ),
    ]
