# Generated by Django 4.2.3 on 2023-11-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0019_alter_st88description_options_st88description_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='st88description',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание ST88'),
        ),
    ]
