# Generated by Django 4.2.3 on 2023-11-09 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0020_alter_st88description_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ST88rating',
        ),
    ]
