# Generated by Django 4.2.3 on 2024-03-14 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0021_delete_st88rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('original_title', models.CharField(max_length=255, verbose_name='Оригинальное название')),
                ('url', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL')),
                ('poster', models.ImageField(upload_to='book/posters/', verbose_name='Постер')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('writer', models.CharField(max_length=255, verbose_name='Писатель')),
                ('genre', models.CharField(max_length=50, verbose_name='Жанр')),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Дата публикации')),
                ('ebook', models.FileField(upload_to='book/ebooks/', verbose_name='Электронная книга')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.AlterField(
            model_name='st88description',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ST88descriptions', to='API.movie', verbose_name='Фильм'),
        ),
        migrations.CreateModel(
            name='FreePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('url', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('subtitle', models.CharField(blank=True, max_length=100, verbose_name='Подзаголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Дата публикации')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='freepost/posters/', verbose_name='Постер')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Пост в свободной форме',
                'verbose_name_plural': 'Посты в свободной форме',
            },
        ),
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='API.book', verbose_name='Книга'),
        ),
        migrations.AddField(
            model_name='st88description',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ST88descriptions', to='API.book', verbose_name='Книга'),
        ),
    ]
