# Generated by Django 4.2.3 on 2024-03-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0022_book_alter_st88description_movie_freepost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freepost',
            name='description',
        ),
        migrations.AddField(
            model_name='freepost',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
    ]
