# Generated by Django 4.2.3 on 2024-04-08 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0023_remove_freepost_description_freepost_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
    ]
