# Generated by Django 4.2.3 on 2024-04-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0025_movie_main_frame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='st88project',
            name='downloaded_film',
        ),
        migrations.AddField(
            model_name='st88project',
            name='linked_trailer',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на трейлер'),
        ),
    ]
