# Generated by Django 4.2.3 on 2024-05-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0026_remove_st88project_downloaded_film_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='related_articles',
            field=models.ManyToManyField(related_name='related_movies', to='API.article', verbose_name='Связанные статьи'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='original_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Оригинальное название'),
        ),
    ]
