# Generated by Django 4.2.3 on 2024-05-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0027_movie_related_articles_alter_movie_original_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='book',
            name='ebook',
            field=models.FileField(blank=True, null=True, upload_to='book/ebooks/', verbose_name='Электронная книга'),
        ),
        migrations.AlterField(
            model_name='book',
            name='original_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Оригинальное название'),
        ),
    ]
