# Generated by Django 4.2.3 on 2024-06-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0028_alter_article_subtitle_alter_book_ebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='synopsys',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое содержание'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='related_articles',
            field=models.ManyToManyField(blank=True, related_name='related_movies', to='API.article', verbose_name='Связанные статьи'),
        ),
    ]
