# Generated by Django 4.2.3 on 2024-06-14 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0029_alter_article_synopsys_alter_movie_related_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='st88project',
            name='authors',
        ),
        migrations.AddField(
            model_name='st88project',
            name='actors',
            field=models.ManyToManyField(blank=True, null=True, related_name='ST88_projects_actor', to=settings.AUTH_USER_MODEL, verbose_name='Актёры'),
        ),
        migrations.AddField(
            model_name='st88project',
            name='cinematographers',
            field=models.ManyToManyField(blank=True, null=True, related_name='ST88_projects_cinematographer', to=settings.AUTH_USER_MODEL, verbose_name='Оператор'),
        ),
        migrations.AddField(
            model_name='st88project',
            name='designers',
            field=models.ManyToManyField(blank=True, null=True, related_name='ST88_projects_designer', to=settings.AUTH_USER_MODEL, verbose_name='Художник'),
        ),
        migrations.AddField(
            model_name='st88project',
            name='directors',
            field=models.ManyToManyField(blank=True, null=True, related_name='ST88_projects_director', to=settings.AUTH_USER_MODEL, verbose_name='Режиссёр'),
        ),
        migrations.AddField(
            model_name='st88project',
            name='editors',
            field=models.ManyToManyField(blank=True, null=True, related_name='ST88_projects_editor', to=settings.AUTH_USER_MODEL, verbose_name='Монтажёр'),
        ),
        migrations.AddField(
            model_name='st88project',
            name='genre',
            field=models.CharField(max_length=50, null=True, verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='st88project',
            name='length',
            field=models.IntegerField(null=True, verbose_name='Длительность (мин)'),
        ),
        migrations.AddField(
            model_name='st88project',
            name='writers',
            field=models.ManyToManyField(blank=True, null=True, related_name='ST88_projects_writer', to=settings.AUTH_USER_MODEL, verbose_name='Сценарист'),
        ),
    ]
