# Generated by Django 4.2.3 on 2024-06-14 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0030_remove_st88project_authors_st88project_actors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='st88project',
            name='producers',
            field=models.ManyToManyField(blank=True, related_name='ST88_projects_producer', to=settings.AUTH_USER_MODEL, verbose_name='Продюсер'),
        ),
        migrations.AlterField(
            model_name='st88project',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='ST88_projects_actor', to=settings.AUTH_USER_MODEL, verbose_name='Актёры'),
        ),
        migrations.AlterField(
            model_name='st88project',
            name='cinematographers',
            field=models.ManyToManyField(blank=True, related_name='ST88_projects_cinematographer', to=settings.AUTH_USER_MODEL, verbose_name='Оператор'),
        ),
        migrations.AlterField(
            model_name='st88project',
            name='designers',
            field=models.ManyToManyField(blank=True, related_name='ST88_projects_designer', to=settings.AUTH_USER_MODEL, verbose_name='Художник'),
        ),
        migrations.AlterField(
            model_name='st88project',
            name='directors',
            field=models.ManyToManyField(blank=True, related_name='ST88_projects_director', to=settings.AUTH_USER_MODEL, verbose_name='Режиссёр'),
        ),
        migrations.AlterField(
            model_name='st88project',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='ST88_projects_editor', to=settings.AUTH_USER_MODEL, verbose_name='Монтажёр'),
        ),
        migrations.AlterField(
            model_name='st88project',
            name='writers',
            field=models.ManyToManyField(blank=True, related_name='ST88_projects_writer', to=settings.AUTH_USER_MODEL, verbose_name='Сценарист'),
        ),
    ]
