# Generated by Django 4.2.3 on 2024-06-17 08:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0031_st88project_producers_alter_st88project_actors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='st88project',
            name='links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
    ]
