# Generated by Django 4.2.3 on 2024-12-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0032_st88project_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to='user/photo/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='user/avatar/', verbose_name='Автар'),
        ),
    ]
