# Generated by Django 4.2.3 on 2024-12-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0033_profile_photo_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_team',
            field=models.BooleanField(default=False),
        ),
    ]
