# Generated by Django 4.2.3 on 2024-12-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0035_remove_profile_is_team_profile_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sliders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.CharField(null=True, verbose_name='Описание раздела')),
                ('slider', models.ImageField(upload_to='sliders/', verbose_name='Слайдер')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка')),
                ('color', models.CharField(max_length=20, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдеры',
            },
        ),
    ]
