# Generated by Django 4.2.3 on 2025-01-22 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0036_sliders'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='API.st88project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='API.movie', verbose_name='Фильм'),
        ),
        migrations.AlterField(
            model_name='sliders',
            name='link',
            field=models.CharField(max_length=255, null=True, verbose_name='Ссылка'),
        ),
    ]
