# Generated by Django 4.2.3 on 2025-02-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0038_alter_frame_movie_alter_frame_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletype',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='article/types/', verbose_name='Фото типа статьи'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='scenario/posters/', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='text',
            field=models.FileField(blank=True, null=True, upload_to='scenario/texts/', verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='sliders',
            name='description',
            field=models.CharField(blank=True, null=True, verbose_name='Описание раздела'),
        ),
        migrations.AlterField(
            model_name='sliders',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка'),
        ),
    ]
