# Generated by Django 4.2.3 on 2025-03-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0039_alter_articletype_photo_alter_scenario_poster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='end_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год последнего выпуска'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(verbose_name='Год выпуска'),
        ),
    ]
