# Generated by Django 4.2.3 on 2025-03-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0040_movie_end_year_alter_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='end_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Последний год выпуска'),
        ),
        migrations.AddField(
            model_name='st88project',
            name='end_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Последний год выпуска'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='st88project',
            name='year',
            field=models.IntegerField(verbose_name='Год выпуска'),
        ),
    ]
