# Generated by Django 4.2.3 on 2025-04-18 11:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0041_book_end_year_st88project_end_year_alter_book_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None, verbose_name='Связанные источники'),
        ),
        migrations.AddField(
            model_name='movie',
            name='related_links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None, verbose_name='Связанные источники'),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Инстаграм'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Телеграм'),
        ),
        migrations.AddField(
            model_name='profile',
            name='vk_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='В контакте'),
        ),
        migrations.AlterField(
            model_name='st88project',
            name='links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None, verbose_name='Связанные источники'),
        ),
    ]
