# Generated by Django 4.2.3 on 2025-04-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0042_book_links_movie_related_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='subtitle',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(max_length=150, verbose_name='Заголовок'),
        ),
    ]
